# Application name
spring.application.name=RiwiMarket

# Global path
server.servlet.context-path=/api/v1

# Database configurations

spring.datasource.url=jdbc:mysql://simulacro1-camilotejada1-9718.i.aivencloud.com:13046/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_o5MJd1J43dLtAVzbX3j
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# # Dialect
# spring.jpa.database-platform=${DB_PLATFORM}

# Email properties
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=04d20d5f36800a
#spring.mail.password=ddefb279428948
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
